-- Jarvis Academy: student accounts + Learning Brain.
-- Run once in Supabase -> SQL Editor. Safe to re-run.
-- Students sign in with Supabase Auth (email + password). All reads/writes go through
-- the server (service role key), so RLS is enabled with NO public policies:
-- the anon key cannot read any of these tables.

create table if not exists academy_profiles (
  user_id            uuid primary key references auth.users(id) on delete cascade,
  display_name       text not null,
  level              text not null default 'secondary' check (level in ('primary','secondary','university')),
  guardian_confirmed boolean not null default false,   -- "13 or over, or set up by a parent/guardian"
  plan               text not null default 'free',
  created_at         timestamptz not null default now()
);

create table if not exists academy_sessions (
  id          uuid primary key,                         -- generated by the browser per conversation
  user_id     uuid not null references auth.users(id) on delete cascade,
  level       text not null,
  turns       integer not null default 0,
  started_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists academy_sessions_user_month on academy_sessions (user_id, started_at desc);

create table if not exists academy_skills (
  id           bigint generated always as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  subject      text not null,
  topic        text not null,
  confidence   integer not null default 50 check (confidence between 0 and 100),
  attempts     integer not null default 0,
  correct      integer not null default 0,
  last_mistake text,
  updated_at   timestamptz not null default now(),
  unique (user_id, subject, topic)
);

alter table academy_profiles enable row level security;
alter table academy_sessions enable row level security;
alter table academy_skills   enable row level security;
-- (no policies on purpose: service role bypasses RLS, everyone else gets nothing)

-- ===== Parent view (added 2026-10-02). Safe to re-run. =====
alter table academy_profiles add column if not exists role text not null default 'student' check (role in ('student','parent'));

-- One-time codes a student generates to share progress with a parent.
create table if not exists academy_invites (
  code        text primary key,
  student_id  uuid not null references auth.users(id) on delete cascade,
  expires_at  timestamptz not null
);

-- Parent <-> student links. Parents see summaries (progress, topics), never chat text.
create table if not exists academy_links (
  parent_id   uuid not null references auth.users(id) on delete cascade,
  student_id  uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (parent_id, student_id)
);
alter table academy_invites enable row level security;
alter table academy_links   enable row level security;
