// HireSign web app service worker (generated by web/build-web.js, build 1.0.0-202610062103).
const CACHE = 'hiresign-1.0.0-202610062103';
const FILES = ["/apps/hiresign","app.js","icon.png","icons/icon-180.png","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","ink.js","manifest.webmanifest","styles.css","THIRD-PARTY-NOTICES.txt","vendor/docx-preview.min.js","vendor/html2canvas.min.js","vendor/jszip.min.js","vendor/nacl-fast.min.js","vendor/pdf-lib.min.js","vendor/pdf.min.mjs","vendor/pdf.worker.min.mjs","web-api.js"];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('hiresign-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    // The page itself: newest when online, cached copy when offline.
    e.respondWith(fetch(req).then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put('/apps/hiresign', copy)); return res; }).catch(() => caches.match('/apps/hiresign')));
    return;
  }
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
